import React from 'react';
import { mount } from 'enzyme';
import Root from '../store';
import App from '../components/App';
import moxios from 'moxios';

beforeEach(() => {
	moxios.install();
	moxios.stubRequest('https://jsonplaceholder.typicode.com/comments', {
		status: 200,
		response: [
			{ name: 'Fake data generated by MOXIOS #1' },
			{ name: 'Fake data generated by MOXIOS #2' }
		]
	});
});

afterEach(() => {
	moxios.uninstall();
});

it('can fetch a list of comments and display them', (done) => {
	// Attempt to render the entire app
	const wrapped = mount(
		<Root>
			<App />/
		</Root>
	);

	// Find the fetchComments button and click
	wrapped.find('button').at(1).simulate('click');

	// Introduce a tiny little pause
	moxios.wait(() => {
		// Expect to find a list of comments
		wrapped.update();
		expect(wrapped.find('li').length).toEqual(2);
	
        done();
		wrapped.unmount();
	});
});
